import { Category, Product, Coupon } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-veg',
    name: 'Vegetables',
    slug: 'vegetables',
    description: 'Farm-harvested fresh greens, root vegetables, and daily staples picked at peak crispness.',
    image: '/images/categories/vegetables.webp',
    order: 1,
  },
  {
    id: 'cat-fruits',
    name: 'Fruits',
    slug: 'fruits',
    description: 'Naturally ripened, sun-kissed fruits bursting with vitamins, sweetness, and hydration.',
    image: '/images/categories/fruits.webp',
    order: 2,
  },
  {
    id: 'cat-grains',
    name: 'Grains & Staples',
    slug: 'grains-staples',
    description: 'Unpolished pulses, stone-ground flours, and heirloom rice varieties from trusted growers.',
    image: '/images/categories/grains.webp',
    order: 3,
  },
  {
    id: 'cat-essentials',
    name: 'Grocery Essentials',
    slug: 'grocery-essentials',
    description: 'Pure cold-pressed oils, artisanal raw honey, dairy essentials, and natural kitchen seasonings.',
    image: '/images/categories/essentials.webp',
    order: 4,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // --- Vegetables ---
  {
    id: 'prod-spinach',
    name: 'Crisp Baby Spinach (Palak)',
    slug: 'crisp-baby-spinach',
    description: 'Hydroponically washed and freshly harvested baby spinach with tender stems. Rich in iron, dietary fibre, and antioxidants. Ideal for wholesome smoothies, soups, and traditional curries.',
    shortDescription: 'Farm-fresh tender baby spinach leaves, hydro-cleaned and chemical-free.',
    categoryId: 'cat-veg',
    price: 45,
    compareAtPrice: 55,
    discountPercentage: 18,
    SKU: 'VEG-SPIN-01',
    stockQuantity: 45,
    unit: '250g',
    images: [
      '/images/products/spinach.webp',
    ],
    altText: 'Fresh green organic baby spinach leaves in a natural basket',
    rating: 4.8,
    reviewCount: 38,
    isFeatured: true,
    isActive: true,
    origin: 'Bhavani River Basin, Sathyamangalam',
    shelfLife: '3-4 Days in refrigerator',
    storageNotes: 'Keep in breathable ziplock bag inside crisper drawer',
  },
  {
    id: 'prod-tomato',
    name: 'Vine-Ripened Hybrid Tomatoes',
    slug: 'vine-ripened-hybrid-tomatoes',
    description: 'Plump, firm, and naturally vine-ripened red tomatoes. Perfectly balanced tartness and sweetness, packed with lycopene and vitamin C for your daily culinary curries and salads.',
    shortDescription: 'Naturally ripened, firm red tomatoes loaded with rich natural juice.',
    categoryId: 'cat-veg',
    price: 42,
    compareAtPrice: 50,
    discountPercentage: 16,
    SKU: 'VEG-TOM-02',
    stockQuantity: 120,
    unit: 'kg',
    images: [
      '/images/products/tomatoes.webp',
    ],
    altText: 'Fresh red vine-ripened tomatoes',
    rating: 4.7,
    reviewCount: 52,
    isFeatured: true,
    isActive: true,
    origin: 'Sathyamangalam Agro Belt, Tamil Nadu',
    shelfLife: '5-7 Days',
    storageNotes: 'Store at cool room temperature away from direct sunlight',
  },
  {
    id: 'prod-carrots',
    name: 'Crunchy Orange Carrots',
    slug: 'crunchy-orange-carrots',
    description: 'Sweet, soil-cleaned organic carrots with maximum crunch and sweetness. An excellent natural source of beta-carotene and essential vitamins.',
    shortDescription: 'Sweet and crunchy farm-harvested carrots, rich in Vitamin A.',
    categoryId: 'cat-veg',
    price: 55,
    compareAtPrice: 65,
    discountPercentage: 15,
    SKU: 'VEG-CAR-03',
    stockQuantity: 65,
    unit: '500g',
    images: [
      '/images/products/carrots.webp',
    ],
    altText: 'Fresh organic carrots on rustic wooden surface',
    rating: 4.9,
    reviewCount: 41,
    isFeatured: false,
    isActive: true,
    origin: 'Nilgiris Foothills, Sathyamangalam',
    shelfLife: '7-10 Days refrigerated',
    storageNotes: 'Cut greens before storing in the vegetable box',
  },
  {
    id: 'prod-potatoes',
    name: 'Mountain Russet Potatoes',
    slug: 'mountain-russet-potatoes',
    description: 'Naturally cured, dirt-dusted farm potatoes. Great texture with high starch density, ideal for boiling, roasting, or curries without getting soggy.',
    shortDescription: 'Versatile kitchen staple potatoes grown in mineral-rich soil.',
    categoryId: 'cat-veg',
    price: 38,
    compareAtPrice: 45,
    discountPercentage: 15,
    SKU: 'VEG-POT-04',
    stockQuantity: 150,
    unit: 'kg',
    images: [
      '/images/products/potatoes.webp',
    ],
    altText: 'Freshly harvested earthy potatoes',
    rating: 4.6,
    reviewCount: 29,
    isFeatured: false,
    isActive: true,
    origin: 'Hassan Farm Cooperative',
    shelfLife: '14-20 Days',
    storageNotes: 'Keep in dark, dry, ventilated basket away from onions',
  },
  {
    id: 'prod-capsicum',
    name: 'Crisp Green Bell Pepper (Capsicum)',
    slug: 'crisp-green-bell-pepper',
    description: 'Thick-walled, crisp green capsicum packed with zesty freshness. Excellent for stir-fries, fajitas, pizza toppings, and stuffed roast delicacies.',
    shortDescription: 'Thick-walled crunchy bell peppers full of aroma and vitamin C.',
    categoryId: 'cat-veg',
    price: 48,
    compareAtPrice: 60,
    discountPercentage: 20,
    SKU: 'VEG-CAP-05',
    stockQuantity: 40,
    unit: '500g',
    images: [
      '/images/products/capsicum.webp',
    ],
    altText: 'Vibrant fresh green bell peppers',
    rating: 4.8,
    reviewCount: 19,
    isFeatured: true,
    isActive: true,
    origin: 'Western Ghats Polyhouses, Thalavadi, Sathyamangalam',
    shelfLife: '5-7 Days refrigerated',
    storageNotes: 'Store dry in an airtight container',
  },
  {
    id: 'prod-broccoli',
    name: 'Tender Florets Green Broccoli',
    slug: 'tender-florets-green-broccoli',
    description: 'Dense, tightly beaded dark green broccoli florets. Grown without synthetic pesticides, providing rich antioxidants, sulforaphane, and dietary fibre.',
    shortDescription: 'Pesticide-free dense broccoli crowns harvested at sunrise.',
    categoryId: 'cat-veg',
    price: 85,
    compareAtPrice: 110,
    discountPercentage: 22,
    SKU: 'VEG-BROC-06',
    stockQuantity: 30,
    unit: 'piece',
    images: [
      '/images/products/broccoli.webp',
    ],
    altText: 'Fresh green broccoli head with tight beads',
    rating: 4.9,
    reviewCount: 44,
    isFeatured: true,
    isActive: true,
    origin: 'Nilgiri Hills, Tamil Nadu',
    shelfLife: '4-5 Days refrigerated',
    storageNotes: 'Wrap loosely in moist paper towel in fridge',
  },

  // --- Fruits ---
  {
    id: 'prod-apple',
    name: 'Himachal Royal Gala Crisp Apples',
    slug: 'himachal-royal-gala-crisp-apples',
    description: 'Naturally sweet, crisp, and aromatic Royal Gala apples directly sourced from high-altitude Himachal orchards. Wax-free, juicy, and naturally polished.',
    shortDescription: 'High-altitude wax-free sweet and juicy apples from Himachal.',
    categoryId: 'cat-fruits',
    price: 180,
    compareAtPrice: 220,
    discountPercentage: 18,
    SKU: 'FRU-APP-01',
    stockQuantity: 60,
    unit: 'kg',
    images: [
      '/images/products/apples.webp',
    ],
    altText: 'Crisp red Royal Gala apples in orchard sunlight',
    rating: 4.9,
    reviewCount: 88,
    isFeatured: true,
    isActive: true,
    origin: 'Kotgarh Valley, Himachal Pradesh',
    shelfLife: '10-14 Days',
    storageNotes: 'Refrigerate to preserve juiciness and crisp snap',
  },
  {
    id: 'prod-banana',
    name: 'Ripe Robusta Mountain Bananas',
    slug: 'ripe-robusta-mountain-bananas',
    description: 'Ethylene-free naturally ripened Robusta bananas. High in potassium, energy, and prebiotic dietary fibres. Uniform golden peel and creamy sweet bite.',
    shortDescription: 'Naturally tree-ripened bananas with creamy sweet pulp.',
    categoryId: 'cat-fruits',
    price: 55,
    compareAtPrice: 65,
    discountPercentage: 15,
    SKU: 'FRU-BAN-02',
    stockQuantity: 80,
    unit: 'pack', // 1 dozen
    images: [
      '/images/products/bananas.webp',
    ],
    altText: 'Golden ripe bananas bunch',
    rating: 4.8,
    reviewCount: 65,
    isFeatured: true,
    isActive: true,
    origin: 'Sathyamangalam & Bhavani River Belt, Tamil Nadu',
    shelfLife: '3-4 Days at room temperature',
    storageNotes: 'Do not refrigerate; hang in ventilated basket',
  },
  {
    id: 'prod-orange',
    name: 'Nagpur Sweet Juicy Oranges',
    slug: 'nagpur-sweet-juicy-oranges',
    description: 'Renowned Nagpur mandarin oranges bursting with zesty citrus juice. Thin peeled and easy to segment, providing 100% of your daily Vitamin C in two fruits.',
    shortDescription: 'Hand-picked Nagpur citrus oranges loaded with refreshing juice.',
    categoryId: 'cat-fruits',
    price: 95,
    compareAtPrice: 120,
    discountPercentage: 20,
    SKU: 'FRU-ORA-03',
    stockQuantity: 50,
    unit: 'kg',
    images: [
      '/images/products/oranges.webp',
    ],
    altText: 'Vibrant sweet Nagpur oranges with citrus leaves',
    rating: 4.7,
    reviewCount: 33,
    isFeatured: false,
    isActive: true,
    origin: 'Nagpur Organic Belt, Maharashtra',
    shelfLife: '6-8 Days',
    storageNotes: 'Store in cool ambient room or fruit rack',
  },
  {
    id: 'prod-pomegranate',
    name: 'Ruby Red Bhagwa Pomegranates',
    slug: 'ruby-red-bhagwa-pomegranates',
    description: 'Grade-A Bhagwa cultivar pomegranates filled with deep red, soft-seeded arils. Unbeatable sweetness and packed with heart-healthy polyphenols.',
    shortDescription: 'Deep red, soft-seeded sweet pomegranate arils rich in antioxidants.',
    categoryId: 'cat-fruits',
    price: 165,
    compareAtPrice: 195,
    discountPercentage: 15,
    SKU: 'FRU-POM-04',
    stockQuantity: 35,
    unit: 'kg',
    images: [
      '/images/products/pomegranate.webp',
    ],
    altText: 'Fresh sliced pomegranate showing ruby arils',
    rating: 4.9,
    reviewCount: 47,
    isFeatured: true,
    isActive: true,
    origin: 'Solapur Orchards',
    shelfLife: '10-15 Days',
    storageNotes: 'Keep in ventilated cool spot',
  },

  // --- Grains & Staples ---
  {
    id: 'prod-basmati',
    name: 'Aged Royal Basmati Rice (Extra Long)',
    slug: 'aged-royal-basmati-rice',
    description: 'Authentic 2-year naturally aged Himalayan basmati rice. Slender, pearlescent grains that elongate to more than double their length upon cooking without sticking.',
    shortDescription: 'Naturally aged extra-long aromatic basmati rice for fragrant biryanis and pulao.',
    categoryId: 'cat-grains',
    price: 145,
    compareAtPrice: 175,
    discountPercentage: 17,
    SKU: 'GRN-BAS-01',
    stockQuantity: 75,
    unit: 'kg',
    images: [
      '/images/products/basmati-rice.webp',
    ],
    altText: 'Slender grains of aromatic raw basmati rice in wooden bowl',
    rating: 4.9,
    reviewCount: 92,
    isFeatured: true,
    isActive: true,
    origin: 'Foothills of Dehradun',
    shelfLife: '12 Months',
    storageNotes: 'Store in airtight steel or glass jar in dry pantry',
  },
  {
    id: 'prod-atta',
    name: 'Chakki-Fresh Sharbati Whole Wheat Atta',
    slug: 'sharbati-whole-wheat-atta',
    description: 'Slow cold-milled traditional stone chakki whole wheat flour. 100% whole grain with bran and germ intact, producing soft, puffed rotis that stay fluffy for hours.',
    shortDescription: '100% stone-ground Sharbati wheat flour with bran intact.',
    categoryId: 'cat-grains',
    price: 68,
    compareAtPrice: 80,
    discountPercentage: 15,
    SKU: 'GRN-ATT-02',
    stockQuantity: 110,
    unit: 'kg',
    images: [
      '/images/products/atta.webp',
    ],
    altText: 'Stone ground whole wheat flour in ceramic bowl',
    rating: 4.8,
    reviewCount: 64,
    isFeatured: false,
    isActive: true,
    origin: 'Sehore, Madhya Pradesh',
    shelfLife: '3 Months',
    storageNotes: 'Store in airtight moisture-free container',
  },
  {
    id: 'prod-toor-dal',
    name: 'Unpolished Organic Toor Dal (Arhar)',
    slug: 'unpolished-organic-toor-dal',
    description: 'Premium unpolished toor dal processed without synthetic oils, water, or coloring agents. Retains natural yellow hue, aroma, and high plant-based protein content.',
    shortDescription: 'Natural oil-free unpolished yellow toor dal with high protein.',
    categoryId: 'cat-grains',
    price: 160,
    compareAtPrice: 185,
    discountPercentage: 13,
    SKU: 'GRN-TOOR-03',
    stockQuantity: 55,
    unit: 'kg',
    images: [
      '/images/products/toor-dal.webp',
    ],
    altText: 'Organic golden toor dal pulses',
    rating: 4.8,
    reviewCount: 39,
    isFeatured: true,
    isActive: true,
    origin: 'Gulbarga, Karnataka',
    shelfLife: '9 Months',
    storageNotes: 'Store in dry place with airtight lid',
  },
  {
    id: 'prod-mustard-oil',
    name: 'Wood-Pressed Kacchi Ghani Mustard Oil',
    slug: 'wood-pressed-mustard-oil',
    description: 'Extracted using traditional wooden expellers (kolhu) below 38°C to retain natural pungency, essential fatty acids, and high smoke point for authentic Indian cooking.',
    shortDescription: 'Raw, unrefined cold-pressed mustard oil with natural pungency.',
    categoryId: 'cat-grains',
    price: 215,
    compareAtPrice: 250,
    discountPercentage: 14,
    SKU: 'GRN-MUST-04',
    stockQuantity: 40,
    unit: 'litre',
    images: [
      '/images/products/mustard-oil.webp',
    ],
    altText: 'Golden cold pressed edible oil in glass bottle',
    rating: 4.9,
    reviewCount: 51,
    isFeatured: false,
    isActive: true,
    origin: 'Alwar, Rajasthan',
    shelfLife: '12 Months',
    storageNotes: 'Store in cool, dark place away from heat',
  },

  // --- Grocery Essentials ---
  {
    id: 'prod-honey',
    name: '100% Pure Raw Wildflower Forest Honey',
    slug: 'raw-wildflower-forest-honey',
    description: 'Unpasteurized and unprocessed raw honey harvested by tribal beekeepers from pristine forest flora. Naturally contains bee pollen, beneficial enzymes, and rich amber warmth.',
    shortDescription: 'Raw, unfiltered forest honey with active enzymes and natural pollen.',
    categoryId: 'cat-essentials',
    price: 320,
    compareAtPrice: 390,
    discountPercentage: 18,
    SKU: 'ESS-HON-01',
    stockQuantity: 35,
    unit: '500g',
    images: [
      '/images/products/honey.webp',
    ],
    altText: 'Raw organic golden honey drizzling from wooden dipper',
    rating: 5.0,
    reviewCount: 77,
    isFeatured: true,
    isActive: true,
    origin: 'Sathyamangalam Forest Reserve & Nilgiri Foothills',
    shelfLife: '24 Months (Never spoils)',
    storageNotes: 'Store at room temperature; do not microwave or refrigerate',
  },
  {
    id: 'prod-ghee',
    name: 'Bilona A2 Desi Cow Cultured Ghee',
    slug: 'bilona-a2-desi-cow-cultured-ghee',
    description: 'Handcrafted using the ancient Ayurvedic Bilona method from curd of free-grazing indigenous Gir cows. Granular golden texture, nutty aroma, and rich in butyric acid.',
    shortDescription: 'Traditional bilona-churned golden ghee made from pure A2 curd.',
    categoryId: 'cat-essentials',
    price: 680,
    compareAtPrice: 790,
    discountPercentage: 14,
    SKU: 'ESS-GHEE-02',
    stockQuantity: 28,
    unit: '500g',
    images: [
      '/images/products/ghee.webp',
    ],
    altText: 'Pure golden desi ghee in traditional glass jar',
    rating: 5.0,
    reviewCount: 84,
    isFeatured: true,
    isActive: true,
    origin: 'Kangayam Organic Dairy Belt, Erode',
    shelfLife: '12 Months',
    storageNotes: 'Store in dry place; always use clean dry spoon',
  },
  {
    id: 'prod-salt',
    name: 'Himalayan Mineral Pink Rock Salt (Fine)',
    slug: 'himalayan-mineral-pink-rock-salt',
    description: 'Unrefined, chemical-free pink rock salt hand-mined from primordial beds. Contains 84 trace minerals including calcium, magnesium, and potassium for clean savory flavor.',
    shortDescription: 'Pure mineral-rich unrefined pink salt containing 84 trace elements.',
    categoryId: 'cat-essentials',
    price: 65,
    compareAtPrice: 85,
    discountPercentage: 23,
    SKU: 'ESS-SALT-03',
    stockQuantity: 90,
    unit: 'kg',
    images: [
      '/images/products/pink-salt.webp',
    ],
    altText: 'Pure pink Himalayan rock salt crystals',
    rating: 4.9,
    reviewCount: 36,
    isFeatured: false,
    isActive: true,
    origin: 'Himalayan Salt Range',
    shelfLife: 'Indefinite',
    storageNotes: 'Keep sealed in moisture-proof ceramic or glass container',
  },
  {
    id: 'prod-eggs',
    name: 'Pasture-Raised Free-Range Brown Eggs',
    slug: 'pasture-raised-free-range-brown-eggs',
    description: 'Fresh farm eggs laid by hens free to forage naturally on lush pastures and sunlight. Deep orange yolks rich in Omega-3 and natural Vitamin D. Antibiotic and hormone free.',
    shortDescription: 'Antibiotic-free pasture raised brown eggs with vibrant orange yolks.',
    categoryId: 'cat-essentials',
    price: 115,
    compareAtPrice: 130,
    discountPercentage: 11,
    SKU: 'ESS-EGG-04',
    stockQuantity: 40,
    unit: 'pack', // 6 eggs
    images: [
      '/images/products/eggs.webp',
    ],
    altText: 'Farm fresh brown eggs in eco-friendly carton',
    rating: 4.9,
    reviewCount: 49,
    isFeatured: true,
    isActive: true,
    origin: 'Coimbatore Free-Range Farm',
    shelfLife: '14 Days refrigerated',
    storageNotes: 'Store in main refrigerator shelf, not door',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-welcome',
    code: 'FARMFRESH10',
    description: '10% off on your entire grocery order (Min order ₹399)',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 399,
    maxDiscount: 100,
    isActive: true,
  },
  {
    id: 'coup-save50',
    code: 'FREESHIP',
    description: 'Flat ₹40 delivery discount on orders above ₹299',
    discountType: 'FIXED',
    discountValue: 40,
    minOrderValue: 299,
    maxDiscount: 40,
    isActive: true,
  },
  {
    id: 'coup-harvest',
    code: 'HARVEST15',
    description: '15% seasonal discount on orders above ₹799',
    discountType: 'PERCENTAGE',
    discountValue: 15,
    minOrderValue: 799,
    maxDiscount: 150,
    isActive: true,
  },
];

export const DEMO_REVIEWS = [
  {
    id: 'rev-1',
    userName: 'Priya Sundaram',
    rating: 5,
    comment: 'The baby spinach arrived completely fresh and crisp, without any damp rot. You can taste the genuine farm difference!',
    productName: 'Crisp Baby Spinach (Palak)',
    isDemo: true,
  },
  {
    id: 'rev-2',
    userName: 'Rajesh Nair',
    rating: 5,
    comment: 'The A2 Desi Cow Ghee aroma took me back to my grandmother’s kitchen. Superb grain and nutty flavor.',
    productName: 'Bilona A2 Desi Cow Cultured Ghee',
    isDemo: true,
  },
  {
    id: 'rev-3',
    userName: 'Ananya Verma',
    rating: 5,
    comment: 'Ordered basmati rice and unpolished toor dal. Prompt delivery, pristine packaging with no synthetic scents.',
    productName: 'Aged Royal Basmati Rice',
    isDemo: true,
  },
];
